language: go
go:
- '1.10'
script:
- go build
deploy:
  provider: heroku
  api_key:
    secure: F9hd7BlzdpN7EQyCCuKftyyWdLjGoeVENtV7RWAgHccu4Em04KipQaGAA8aWQvlNDNtGM91wYZNf0ocUDz9KrMOgQ2FWYyYmbm0+2PyHESXrm1ewpYY6w5ncjlNJi7dnhkKec1Y/rePK+Co08UBLJXNAsqg9qHwtZyJnHYLsuVupd8L95+hgzv5xdNKnD/qKAjV+3+WnYYbq99/W2tubKh/mIvfsbhaFXH42GSE25+d/yDT5PPg4TO45GsYsfOqjSXs6xJg15DQoXtfCkXqIdUtvbL/Hh4/lklDVpiQ0Jq3N0paTxOHINS6ysUAYsm5RMFA4TuuXeSs6XlVfPhVSwXAvjOL/xkKZ4QlF3xJIHATWmSMmzvb6YoGoQsTwUjBKjPKxFO52hQDnZbes3YudfuY6sbEVOB1t82fOM4G3a80SROY1Xp0KpWISA/dTBoIaV309VINhgYL5mNZVqUsDgAFrBSxYjUVlAaui+1x/7SrFvUopUscRtCJKVVxd/UblIAsXLm6E3Fld7DXwhwwFcLZXmD8LhVMzveywwJlQBSweO7spJMsKXuftyN97XdR3cQLgLcNQfzmmEDOHwMhvSmFFewxs7DhDSgwD8q40oXlP4vjs2TV/YrwbJ8eb6JMhvVHUMR6kEo/qBYrLM4xRuxg8XhAYNazyZAkTi4FU+HI=
  app: whispering-badlands-32857
  on:
    repo: missKsu/RSOI_Lab1_1
