language: go
go:
- '1.8'
script:
- go build
deploy:
  provider: heroku
  api_key:
    secure: j6PgFLlcVndLhs0pK5kXLoBRJPvBoTcMBkmvHSEYEMqBEJgBOAy9n9AVksFlDj6qQmAG+fjgAdQBhrAjGZMGlS5I9LCU9PTTRwyTZ4kFw111GXOk7h+OFnWZHZmHXgB36FnSrFsklIx2gidHe5UwbUEsPN/06/0690ViG10xRKESJsKQ0+09FXOKOG1UQnV2WxFo86MVgWT7u95yB8E/V2MdKe86ZLltvSj/VWZnrH31HL8Z44RvHyU18D+u67/Yd/hbt5dAeP76vAX5uN4epii4lHDM4K+hZevF+EBKeyja+IAJzNti8678tBpu1Yowqwf5Q0sm+GeLMdn/Ka0YsyYWSTBJW0seDj1Whac7UUa+idFgeaOImmQAtPMeAAyCtkieZxFL6Spaw5CaXPsUEzqvnspxAMyogNNxdCEPIpe9Kak/8vhxvS/hI7Ybqu6P6qpYXZmn4XR6RZb6K7IKAUDCgDQq/MVtJ0oolV3mP1UtqzOTzKMiHTc2KRVHEMaKrAD3Onw2RR0/+bi6C8Re8ci7MXYE8R88F7Nbfv7l0kQGqASizZPMjn5ad3J39Wd5N4xQxsvpPuypQFB4/hjyqURXsjpLglYqVCWzFZgo5Lb/8XBf68hvI+47Hqlj/Xkm3I56dw0nGpJPmHmi5/u0s4P13Pn/p7vH/5l1i/kQifw=