language: go
go:
- '1.8'
script:
- go build
deploy:
  provider: heroku
  api_key:
    secure: MFj2pe2/QUCLDCn2iLuBrHusZe0fHiVdEBMmyu253ZFY+1ND9LEbQD1OuAXpmRdNDGBznWNwSlLpU+C0kWwvCzclbFsiP/EvVsiygV5hftKOjMx51rsfoCo5UKQRXWn5PCNsEeH4Ywwgeq0+MFSKSacZRQTDiU/1fGEGgCgrznOAbbYzjbaYJHBLHifCJgZBD1g1JDyuuTSlazwixGueoW10782K7ttfY4VsQWLh0QDJeSr4lLgwQ4i38HoK+I5UbbVmpQ7Gk/JC17yZY2fx8eI5+FOMNDBABBTOBoVJYc7htGQfMcaYeJ5+hpNSecNpOE60UjfKUbGRrwooAGi+GA9F0L6TRPEwzxZ1G7Ec25y2mZ92fF0kHhFjY5T/cmXczezqTKMFehFbXLP/CTGWj3y8jk7bpHxdmZRTtp7EKiGgV0PZILX8rUfkppksANP4Q5fqdB6SCPYDSdvYjxXQgXuSv+8tZN/SJO65oYTyy/PzAoWVDUvdocGxJOzTr4nQ5ONGm6JkHXOJ9NJsAoX0668Zark8JasFrqwQW9mKEiCn+PIepSxy0B0ykfOAevEq/q8qntPoR8pGGQaL36RfJKMZGwesNMqn1e5mtRz4cBrDCNFbujIxvyoeu0Cz4n4D2xonCCKyAh/d+cDY6kmj2h0DZlkcxNg3ez9MF9h2mD0=
  app: whispering-badlands-32857
  on:
    repo: missKsu/RSOI_Lab1_1
