language: go
go:
- '1.8'
script:
- go build
deploy:
  provider: heroku
  api_key:
    secure: H5T87lXcisnN3IFguV+KpTF1Ybvkkm+oflC2URyZnIiq+O7A1HAblc3Z5tiAmsqwIobDA/HNyFmIbNhOed6m/W6pRYty2HqnTs1Y4vk9qkQQ+8OxBgeaQmfxa9jhC2LcsIAJ2ID0DQ23qorZdbBKyItXVpSMe9bzzL5HPsVWjoLZChbEGDeSOejeq9gRQu3iG93Wt9IiCoVeVpDjnfVu5QaM7vq9TJsHEAHk+2xWXEPwUiiXIT8RBHNeOlOcHLt28pMA5u0G6ykoNDat78+fzV08T7ekruXPPTw5p+wIWtSR7esH42eb8C+TL+L50i3PUHLYL10sI7AKZj689R65Z7I4FifxfVH0dQRSH1SYVdxUxZ++c1Gpc3dprNV9TjOJbnski5mlVoK15YIzy1jfzqMHb1kYueBy16wrSYjolztZ8hijtoAeq5pOaNAxuIZOkOLrpGvq5H9PHFc5uN/FXMn2MEn48qoshSkBDx0TTV9d3DuuPOypWfblB2INFDUzsDpNjOzUHe2R4Q5ohuqd4ycw0i9/u9kT8dCqUnk5pXkhnnS712KQcggSGyYzw/ZMI59ezFqW1j5F+Y4i/ASU1nk4SscVSRTVzsb0H/hhLXkvFymMjhbHNCiL6uJfDLaU7U234399lczAUADpVtu8zkQh5+S/Ec4KKxqj+v62EW0=
