language: go
go:
- '1.10'
script:
- go test
- go build
deploy:
  provider: heroku
  api_key:
    secure: nIBuVWcdvMefep1bkRJBKHTFn7X5hhtO7WEWt8uU+DRR70Cpr3CKzADNU7XUYPocdyWwMY4fzqtkLNJbZCDM5rOU4yIzwLddd++iYBPpjFrZuYNXHkAlh1Cqp9tN5s6TYq4YMQn89MaFojzVNf57iTDWmEoFK8SxttxeojMsRK5+XDHhWfeQawuFACxuTIQMA1DFMx4bUNHJxOVgp17WtLA6HUjYZLQwtjt7vXYASeuK+36/POK0ABHKQDY+cpZSgiO18LQrTtjAQwISVAbCWv3VUr2RmxRlJxkEP86cZMoMHcKG0IybH75KacNQmWAUbU9UqWAma7lvfmJROiqBkIT9TNyTCtwaGoEriDTRxrEQ/TIy/POalrEP5hya9d6XrzFL4lHNmhmSAIKfPXvDmrLkHK77+SK46izVnzDgziGqqpTnPrBPisBgP1npSV4NC66xnTV61pusW0UoqBemvtKhyONyOAB3kuPCeSnxFz1V5Bx5ANlxYn4WfDl5kJNzXBhxREz+fzCEMaulkT5aaHuSEM6Tvzqci/GpSy/hq2z3s+l570kGLwaTH+KDJ0sbPYB93lW+6Ee8BxTpYBSQ5PzeCeBgbYNyEOsvQmu+Ebq1cw3IxEBn6cEwzkO68uZWe09zIwyrdtR6wwm3JH60UwFPhsoWhLiUnyFast3ldfo=
  app: whispering-badlands-32857
  on:
    repo: missKsu/RSOI_Lab1_1
  skip_cleanup: true